// lib/game/v2/defaultThemes.ts
// Banco local de temas (V0/V2). Pode ser expandido e depois migrado para Prisma.
// Importante: Fase 1 e Fase 2 são bancos separados (não intercambiáveis).

export const PHASE1_THEMES: string[] = [
  'Coisas para fazer num dia de chuva',
  'Coisas para fazer num domingo preguiçoso',
  'Coisas para fazer quando falta energia',
  'Coisas para fazer quando você está entediado',
  'Coisas para fazer com pouco dinheiro',
  'Coisas para fazer em 10 minutos',
  'Coisas para fazer antes de dormir',
  'Coisas para fazer ao acordar',
  'Coisas para fazer numa fila gigante',
  'Coisas para fazer numa viagem de carro longa',
  'Coisas para fazer quando você quer impressionar alguém',
  'Coisas para fazer pra recuperar o foco',
  'Coisas para fazer quando você está ansioso',
  'Coisas para fazer pra levantar o astral',
  'Coisas para fazer com amigos em casa',
  'Coisas para fazer sozinho (sem celular)',
  'Coisas para fazer no intervalo do trabalho',
  'Coisas para fazer quando você perdeu o ônibus',

  //Dos antigos
   'Coisas para fazer num dia de chuva',
  'Coisas para fazer quando falta energia',
  'Coisas para fazer quando você está entediado',
  'Coisas para fazer sozinho (sem celular)',
  'Coisas para fazer com amigos em casa',
  'Coisas para fazer com pouco dinheiro',
  'Coisas para fazer em 10 minutos',
  'Coisas para fazer antes de dormir',
  'Coisas para fazer ao acordar',
  'Coisas para fazer quando você perdeu o ônibus',
  'Coisas para fazer enquanto espera alguém atrasado',
  'Coisas para fazer numa fila gigante',
  'Coisas para fazer num aeroporto (sem surtar)',
  'Coisas para fazer numa viagem de carro longa',
  'Coisas para fazer no intervalo do trabalho',
  'Coisas para fazer quando você quer impressionar alguém',
  'Coisas para fazer para levantar o astral',
  'Coisas para fazer pra recuperar o foco',
  'Coisas para fazer quando você não consegue dormir',
  'Coisas para fazer quando você está com ansiedade',
  'Coisas para fazer quando está calor demais',
  'Coisas para fazer quando está frio demais',
  'Coisas para fazer num dia de “autocuidado”',
  'Coisas para fazer pra ser mais saudável sem drama',
  'Coisas para fazer pra economizar tempo amanhã',
  'Coisas para fazer para organizar a vida em 15 minutos',
  'Coisas para fazer pra dar um reset mental',
  'Coisas para fazer pra ser uma pessoa mais interessante',
  'Coisas para fazer quando você está de ressaca',
  'Coisas para fazer no banheiro (sem ser esquisito)',
  'Coisas para fazer no transporte público',
  'Coisas para fazer enquanto cozinha',
  'Coisas para fazer enquanto lava a louça',
  'Coisas para fazer enquanto arruma o quarto',
  'Coisas para fazer quando o Wi-Fi cai',
  'Coisas para fazer quando o celular está sem bateria',
  'Coisas para fazer quando você está esperando um e-mail importante',
  'Coisas para fazer depois de uma discussão',
  'Coisas para fazer antes de pedir desculpas',
  'Coisas para fazer pra quebrar o gelo numa festa',
  'Coisas para fazer num encontro (primeiro date)',
  'Coisas para fazer num encontro longo (3+ horas)',
  'Coisas para fazer em casal em casa',
  'Coisas para fazer com a família num feriado',
  'Coisas para fazer com crianças por perto',
  'Coisas para fazer pra ajudar alguém hoje',
  'Coisas para fazer com a letra A',
  'Coisas para fazer com um objeto aleatório (uma caneca)',
  'Coisas para fazer olhando pela janela por 2 minutos',
  'Coisas para fazer para aprender algo novo sem curso',
  'Coisas para fazer pra ficar mais confiante',
  'Coisas para fazer pra ter uma conversa melhor',
  'Coisas para fazer numa cidade que você não conhece',
  'Coisas para fazer numa praia (sem cair no golpe do milho caro)',
  'Coisas para fazer num parque',
  'Coisas para fazer quando chove e você está sem guarda-chuva',
  'Coisas para fazer quando você esqueceu sua senha',
  'Coisas para fazer quando você está com fome mas sem vontade de cozinhar',

  // STOP style (letras mais “jogáveis”)
  'Coisas para fazer com a letra A',
  'Coisas para fazer com a letra B',
  'Coisas para fazer com a letra C',
  'Coisas para fazer com a letra D',
  'Coisas para fazer com a letra E',
  'Coisas para fazer com a letra F',
  'Coisas para fazer com a letra G',
  'Coisas para fazer com a letra L',
  'Coisas para fazer com a letra M',
  'Coisas para fazer com a letra P',
  'Coisas para fazer com a letra R',
  'Coisas para fazer com a letra S',
  'Coisas para fazer com a letra T',

  // Mais temas (pra não acabar no meio do caos)
  'Coisas para fazer para animar alguém',
  'Coisas para fazer para pedir desculpas',
  'Coisas para fazer para flertar sem vergonha',
  'Coisas para fazer para se acalmar em 60 segundos',
  'Coisas para fazer para se sentir mais corajoso',
  'Coisas para fazer para agradecer alguém',
  'Coisas para fazer para ganhar tempo',
  'Coisas para fazer para matar saudade',
  'Coisas para fazer para se reconciliar com um amigo',
  'Coisas para fazer para impressionar com zero dinheiro',
  'Coisas para fazer para transformar um dia ruim',
  'Coisas para fazer para fugir do tédio no trabalho',
  'Coisas para fazer para deixar o ambiente mais leve',
  'Coisas para fazer para “puxar assunto”',
  'Coisas para fazer para animar um grupo',
  'Coisas para fazer para fazer alguém rir',
  'Coisas para fazer para se distrair sem tela',
  'Coisas para fazer para treinar criatividade',
  'Coisas para fazer para recuperar energia',
  'Coisas para fazer quando você quer sumir por 5 minutos',
  'Coisas para fazer quando você está com preguiça de viver',
  'Coisas para fazer quando a internet cai',
  'Coisas para fazer numa madrugada acordado',
  'Coisas para fazer num encontro em casa',
  'Coisas para fazer em família',
  'Coisas para fazer num rolê barato',
  'Coisas para fazer numa praia lotada',
  'Coisas para fazer numa trilha',
  'Coisas para fazer para “quebrar o gelo”',
  'Coisas para fazer quando alguém diz “preciso te contar uma coisa”',
  'Coisas para fazer quando você erra feio',
  'Coisas para fazer quando você quer parecer misterioso',
  'Coisas para fazer para celebrar uma pequena vitória',
];

export const PHASE2_THEMES: string[] = [
  'A pior coisa para se fazer quando você encontra seu ex',
  'A primeira coisa a se fazer ao descobrir que ganhou poderes',
  'A coisa mais absurda para se fazer num velório',
  'A última coisa a fazer quando o chefe diz “rapidinho”',
  'A pior coisa para se dizer num primeiro encontro',
  'A pior coisa para se fazer num casamento (sem ser preso)',
  'A coisa mais inadequada para fazer numa entrevista de emprego',
  'A pior forma de pedir desculpas',
  'A coisa mais caótica para fazer numa sala de aula',
  'A pior coisa para fazer quando o avião tem turbulência',
  'A última coisa que você faria antes de apertar “enviar”',
  'A pior coisa para fazer quando alguém diz “confia”',
  'A coisa mais estranha para fazer ao conhecer os sogros',
  'O melhor jeito de arruinar uma festa surpresa',
  'A pior coisa para fazer quando você está tentando ser discreto',
  'A coisa mais absurda para fazer para “animar alguém”',
  'A pior coisa para fazer quando você está perdido',
  'A última coisa para fazer quando você quer parecer inteligente',
  'A pior coisa para fazer num elevador cheio',
  'A coisa mais inadequada para fazer durante uma reunião séria',
  'O jeito mais rápido de destruir uma amizade (sem querer)',
  'A última coisa para fazer quando você tenta ser romântico',
  'A pior coisa para fazer quando você precisa “agir normal”',

  //Dos antigos
  'Pior coisa para se fazer num velório',
  'A última coisa que você faria num apocalipse zumbi',
  'A coisa menos apropriada para se fazer numa entrevista de emprego',
  'A coisa mais absurda para se fazer numa reunião importante',
  'Primeira coisa a se fazer ao acordar em Marte',
  'A coisa mais suspeita para se fazer numa biblioteca silenciosa',
  'A coisa menos heroica para se fazer ao salvar o mundo',
  'A coisa mais cafona para se fazer num casamento chique',
  'A coisa mais perigosa para se fazer num laboratório (NÃO façam)',
  'A coisa mais inadequada para se fazer no próprio aniversário surpresa',
  'A coisa mais caótica para se fazer durante uma prova',
  'A pior reação possível ao ouvir “precisamos conversar”',
  'A última coisa a se fazer ao acordar e perceber que mudou de gênero',
  'A coisa mais estranha para se fazer ao conhecer sogros pela primeira vez',
  'A coisa menos inteligente para se fazer quando você se perde numa floresta',
  'A coisa mais injustificável para se fazer numa mesa de RPG',
  'A coisa mais dramática para se fazer numa padaria',
  'A coisa mais suspeita para se fazer num aeroporto',
  'A coisa menos discreta para se fazer numa aula de yoga',
  'A coisa mais engraçada para se fazer num elevador lotado (sem crimes)',
  'A pior coisa para se fazer quando o avião faz um barulho esquisito',
  'A coisa mais absurda para se fazer ao ser abduzido por alienígenas',
  'A coisa menos apropriada para se fazer num interrogatório',
  'A primeira coisa para se fazer quando você vira invisível (por 10 min)',
  'A última coisa que você faria antes do fim do mundo (comédia permitida)',
  'A coisa mais inadequada para se fazer num grupo de WhatsApp da família',
  'A pior coisa para se fazer num jantar romântico',
  'A coisa mais insana para se fazer num banco',
  'A coisa menos útil para se fazer quando o planeta é invadido por robôs',
  'A coisa mais absurda para se fazer ao ganhar na loteria',
  'A coisa mais vergonhosa para se fazer num palco',
  'A pior coisa para se fazer quando você percebe que está ao vivo',
  'A coisa mais suspeita para se fazer num museu',
  'A coisa menos apropriada para se fazer numa sala de espera',
  'A coisa mais sem noção para se fazer numa apresentação em PowerPoint',
  'A coisa menos profissional para se fazer numa call com o chefe',
  'A pior coisa para se fazer quando você é o “médico” em um filme de terror',
  'A coisa mais absurda para se fazer numa nave espacial sem gravidade',
  'A coisa menos apropriada para se fazer durante uma oração',
  'A coisa mais dramática para se fazer ao pedir um lanche',
  'A pior coisa para se fazer quando você está tentando ser discreto',
  'A coisa mais improvável para se fazer ao se tornar rei/rainha por 1 dia',
  'A coisa menos sensata para se fazer num cassino em Las Vegas',
  'A coisa mais caótica para se fazer numa sala de aula',
  'A pior coisa para se fazer quando você tenta impressionar alguém',
  'A coisa mais suspeita para se fazer numa delegacia',
  'A coisa menos apropriada para se fazer num reality show',
  'A coisa mais absurda para se fazer quando você tem superpoderes',
  'A pior coisa para se fazer quando o microfone está aberto',
  'A coisa menos apropriada para se fazer no Natal em família',
  'A coisa mais absurda para se fazer ao ser promovido',
  'A primeira coisa a se fazer ao descobrir que está sonhando',


  //Umas pesadas 
  'A coisa mais saudável a se fazer num campo de concentração',
  'A última coisa a se fazer ao descobrir que seu filho é hétero',
  'A coisa mais fácil de se fazer com uma mão só',
  'A coisa que você aprende fazer automaticamente ao virar pai',
  'A coisa mais nazista que alguém poderia fazer',
  'A coisa mais difícil que eu conseguiria fazer após ficar 12 dias sem cagar',
  'A coisa mais divertida que alguém já fez sendo pobre',
  'A coisa mais heróica que se pode fazer ao tomar uma bala perdida',
  'A primeira coisa a se fazer ao descobrir que está num pesadelo',
  'A coisa mais sensta a se fazer ao abrir os olhos e perceber que estavam te exorcisando',
  'A coisa que dá pra fazer por mais tempo em Chernobyl',
  'A melhor coisa a se fazer ao perceber que está sendo perceguido',
  'A coisa mais honesta a se fazer após reagir a um assalto',
  'A pior coisa a se fazer quando você está assaltando e a vítima reage',
  'A primeira coisa a se fazer após levar uma mordida do cão policial no aeroporto',
  'A pior coisa a se fazer sendo careca',
  'A pior coisa a se fazer sendo anão',
  'A coisa mais divertida de se fazer sendo cego',
  'A coisa mais fácil de se fazer sendo gay',
  'A pior coisa a se fazer nos seus segundos finais',
  'A primeira e ultima coisa a se fazer após tirar o capacete, na Lua',
  'A pior coisa a se fazer após prender a pelinha da genitália no zíper da calça',
  'A coisa mais inteligente a se fazer ao ser encarado por um doido',
  'A coisa estranha de se fazer com a bunda de fora',
  'A coisa mais bonita de se fazer ao chegar atrasado e perder o ENEM',
  'A coisa mais elegante a se fazer enquanto o elevador despenca',
  'A coisa mais sábia a se fazer quando o seu celular cai na cabeça de uma criança na arquibancada',
  'A pior coisa a se fazer depois de dizer "relaxa, eu sei o que tô fazendo"',
  'A coisa mais convincente a se dizer quando você é pego mentindo com provas em 4K',
  'A coisa mais produtiva a se fazer no meio de uma crise existencial em público',
  'A primeira coisa a se fazer ao descobrir que o date era uma reunião da Hinodê',
  'A coisa mais honesta a se fazer ao presenciar seu chefe no banheiro tentando, sem sucesso, urinar',
  'A pior coisa a se fazer quando alguém diz "posso ser sincero com você?"',
  'A pior coisa a se fazer durante um pedido de casamento… que não é pra você',
  'A coisa mais corajosa a se fazer quando a moça pergunta se é de aproximar ou de inserir',
  'A coisa mais profética a se fazer quando a menstruação atrasa',
  'A coisa mais digna a se fazer ao tropeçar em público e ouvir risada',
  'A coisa mais absurda a se fazer quando alguém diz "isso é só uma fase"',
  'A melhor coisa a se fazer quando a pessoa te diz "não para"',
  'A coisa mais assustadora a se fazer numa festa onde você só conhece o anfitrião (e ele sumiu)',
  'A pior coisa a se fazer após ser apresentado e falarem que você é uma pessoa super tranquila',
  'A coisa mais filosófica a se fazer quando o efeito da cafeína bate',
  'A pessoa está prester a morrer e você diz que a melhor coisa a se fazer é',
  'A última coisa a se fazer quando o médico pergunta "Isso dói?"',
  'A coisa mais inesperada a se fazer após ser pego se masturbando',
  'A coisa mais questionável a se fazer ao ser presenteado com algo que não gosta',
  'A coisa mais burra a se fazer durante o discurso na sua posse precidencial ',
  'A coisa mais inteligente a se fazer após ser pego colocando algo impróprio no ouvido',
  'A primeira coisa a se fazer ao se tornar Deus',
  'A pior coisa a se fazer após roubarem seu bilhete vencedor da Mega-Sena',


  // Mais prompts (fase 2 vive de volume)
  'A coisa mais absurda para fazer para pedir desculpas',
  'A coisa mais absurda para fazer para flertar',
  'A pior coisa para fazer quando sua mãe diz “cheguei”',
  'A última coisa para fazer quando você quer convencer alguém',
  'A pior resposta possível para “tá tudo bem?”',
  'A coisa mais inadequada para fazer numa consulta médica',
  'A pior coisa para fazer quando você está atrasado',
  'A última coisa para fazer antes de uma prova',
  'A pior coisa para fazer quando você encontra um famoso',
  'A coisa mais estranha para fazer num restaurante chique',
  'A pior coisa para fazer durante uma oração',
  'A pior coisa para fazer quando alguém está chorando',
  'A pior coisa para fazer ao conhecer o sogro pela primeira vez',
  'A coisa mais desastrosa para fazer quando você quer parecer confiante',
  'A última coisa para fazer quando você quer ser lembrado com carinho',
  'A pior coisa para fazer quando você quer evitar conflito',
  'A coisa mais caótica para fazer numa biblioteca',
  'A pior coisa para fazer num cinema lotado',
  'A coisa mais inadequada para fazer num culto / missa',
  'A pior coisa para fazer quando o professor diz “é rápido”',
  'A pior coisa para fazer quando alguém te oferece ajuda',
  'A última coisa para fazer antes de dormir numa casa desconhecida',
  'A pior coisa para fazer quando o Uber pergunta “tá no destino certo?”',
  'A pior coisa para fazer quando a polícia passa',
  'A coisa mais absurda para fazer num aniversário infantil',
  'A última coisa para fazer quando você tenta ser adulto responsável',
  'A pior coisa para fazer quando você está tentando ser fofo',
  'A coisa mais absurda para fazer para “mostrar maturidade”',
  'A pior coisa para fazer quando você quer pedir aumento',
  'A coisa mais inadequada para fazer num churrasco de família',
  'A pior coisa para fazer quando você quer terminar um relacionamento',
  'A pior coisa para fazer quando você quer reatar um relacionamento',
  'A coisa mais absurda para fazer quando você esqueceu o nome de alguém',
  'A última coisa para fazer quando você está tentando ser discreto',
  'A pior coisa para fazer quando você quer ser “low profile”',
  'A coisa mais inadequada para fazer numa formatura',
  'A pior coisa para fazer quando você está com ciúmes',
  'A pior coisa para fazer quando você quer parecer culto',
  'A coisa mais absurda para fazer numa live com 100 pessoas',
  'A coisa que as pessoas mais fazem após ser pego traindo',
  'A coisa mais improvável de um sonâmbulo fazer',
  'A coisa mais inadequada para fazer quando você está em luto',
  'A pior coisa para fazer quando você quer consolar alguém',
  'A pior coisa para fazer quando você quer motivar alguém',
  'A última coisa para fazer quando você quer impressionar o crush',
  'A pior coisa para fazer quando você diz “vou ser honesto”',
  'A coisa mais absurda para fazer numa reunião do condomínio',
];
