// lib/game/v2/defaultThemes.ts
// Banco local de temas (V0/V2). Pode ser expandido e depois migrado para Prisma.
// Importante: Fase 1 e Fase 2 são bancos separados (não intercambiáveis).

export const PHASE1_THEMES: string[] = [
  'Coisas para fazer num dia de chuva',
  'Coisas para fazer num domingo preguiçoso',
  'Coisas para fazer quando falta energia',
  'Coisas para fazer quando você está entediado',
  'Coisas para fazer com pouco dinheiro',
  'Coisas para fazer em 10 minutos',
  'Coisas para fazer antes de dormir',
  'Coisas para fazer ao acordar',
  'Coisas para fazer numa fila gigante',
  'Coisas para fazer numa viagem de carro longa',
  'Coisas para fazer quando você quer impressionar alguém',
  'Coisas para fazer pra recuperar o foco',
  'Coisas para fazer quando você está ansioso',
  'Coisas para fazer pra levantar o astral',
  'Coisas para fazer com amigos em casa',
  'Coisas para fazer sozinho (sem celular)',
  'Coisas para fazer no intervalo do trabalho',
  'Coisas para fazer quando você perdeu o ônibus',

  // STOP style (letras mais “jogáveis”)
  'Coisas para fazer com a letra A',
  'Coisas para fazer com a letra B',
  'Coisas para fazer com a letra C',
  'Coisas para fazer com a letra D',
  'Coisas para fazer com a letra E',
  'Coisas para fazer com a letra F',
  'Coisas para fazer com a letra G',
  'Coisas para fazer com a letra L',
  'Coisas para fazer com a letra M',
  'Coisas para fazer com a letra P',
  'Coisas para fazer com a letra R',
  'Coisas para fazer com a letra S',
  'Coisas para fazer com a letra T',
];

export const PHASE2_THEMES: string[] = [
  'A pior coisa para se fazer quando você encontra seu ex',
  'A coisa mais absurda para se fazer num velório',
  'A última coisa a fazer quando o chefe diz “rapidinho”',
  'A pior coisa para se dizer num primeiro encontro',
  'A pior coisa para se fazer num casamento (sem ser preso)',
  'A coisa mais inadequada para fazer numa entrevista de emprego',
  'A pior forma de pedir desculpas',
  'A coisa mais caótica para fazer numa sala de aula',
  'A pior coisa para fazer quando o avião tem turbulência',
  'A última coisa que você faria antes de apertar “enviar”',
  'A pior coisa para fazer quando alguém diz “confia”',
  'A coisa mais estranha para fazer ao conhecer os sogros',
  'O melhor jeito de arruinar uma festa surpresa',
  'A pior coisa para fazer quando você está tentando ser discreto',
  'A coisa mais absurda para fazer para “animar alguém”',
  'A pior coisa para fazer quando você está perdido',
  'A última coisa para fazer quando você quer parecer inteligente',
  'A pior coisa para fazer num elevador cheio',
  'A coisa mais inadequada para fazer durante uma reunião séria',
  'O jeito mais rápido de destruir uma amizade (sem querer)',
  'A última coisa para fazer quando você tenta ser romântico',
  'A pior coisa para fazer quando você precisa “agir normal”',
];
