import type { ThemeBank } from './types';

export const DEFAULT_THEME_BANK: ThemeBank = {
  version: 'v1',
  updatedAt: Date.now(),

  // FASE 1: sempre começa com "Coisas para fazer ..."
  phase1Themes: [
    'Coisas para fazer num dia de chuva',
    'Coisas para fazer quando falta energia',
    'Coisas para fazer sem internet',
    'Coisas para fazer num domingo à tarde',
    'Coisas para fazer quando você acorda cedo demais',
    'Coisas para fazer numa fila enorme',
    'Coisas para fazer esperando alguém (atrasado)',
    'Coisas para fazer no intervalo de uma aula',
    'Coisas para fazer em 10 minutos livres',
    'Coisas para fazer em 2 minutos livres',
    'Coisas para fazer sem gastar dinheiro',
    'Coisas para fazer com 10 reais',
    'Coisas para fazer com um objeto aleatório (uma caneta, por exemplo)',
    'Coisas para fazer sozinho em casa',
    'Coisas para fazer com amigos em casa',
    'Coisas para fazer antes de dormir',
    'Coisas para fazer quando bate tédio',
    'Coisas para fazer quando você está ansioso',
    'Coisas para fazer para animar alguém',
    'Coisas para fazer para pedir desculpas',
    'Coisas para fazer quando você quer parecer produtivo',
    'Coisas para fazer quando você perde o ônibus',
    'Coisas para fazer quando você esquece um compromisso',
    'Coisas para fazer quando a comida queimou',
    'Coisas para fazer quando você está com fome e sem nada pronto',
    'Coisas para fazer quando você quer se cuidar',
    'Coisas para fazer para melhorar seu dia em 5 minutos',
    'Coisas para fazer pra comemorar uma vitória pequena',
    'Coisas para fazer quando você encontra um conhecido na rua',
    'Coisas para fazer quando você não quer sair mas precisa espairecer',
    'Coisas para fazer quando você está no modo “quero sumir”',
    'Coisas para fazer quando está muito calor',
    'Coisas para fazer quando está muito frio',
    'Coisas para fazer num feriado chato',
    'Coisas para fazer numa viagem de carro',
    'Coisas para fazer numa viagem de ônibus',
    'Coisas para fazer num quarto bagunçado',
    'Coisas para fazer quando você quer arrumar a casa sem sofrer',
    'Coisas para fazer quando você quer fazer alguém sorrir',
    'Coisas para fazer quando você quer aprender algo rápido',
    'Coisas para fazer com a letra A',
    'Coisas para fazer com a letra B',
    'Coisas para fazer sem sair do lugar',
    'Coisas para fazer em silêncio',
    'Coisas para fazer usando só uma mão',
    'Coisas para fazer sem usar as mãos',
    'Coisas para fazer em dupla',
    'Coisas para fazer com amigos (ao ar livre)',
    'Coisas para fazer com a família',
    'Coisas para fazer quando você está esperando uma resposta',
    'Coisas para fazer pra relaxar sem tela',
    'Coisas para fazer quando o celular está sem bateria',
    'Coisas para fazer quando você está com vergonha',
    'Coisas para fazer quando você quer se sentir corajoso',
    'Coisas para fazer quando você quer se sentir inteligente',
    'Coisas para fazer quando tudo parece “meio sem graça”',
    'Coisas para fazer para transformar um dia ruim num dia ok',
    'Coisas para fazer quando você quer recuperar o foco',
    'Coisas para fazer quando você quer se sentir adulto responsável',
    'Coisas para fazer quando você quer economizar tempo amanhã',
    'Coisas para fazer quando você quer surpreender alguém',
    'Coisas para fazer quando você quer reconectar com alguém',
    'Coisas para fazer quando você quer sair do automático',
    'Coisas para fazer quando você está com preguiça, mas vai fazer mesmo assim',
    'Coisas para fazer quando você está com pressa',
    'Coisas para fazer quando você está com tempo de sobra',
    'Coisas para fazer quando você está com sono',
    'Coisas para fazer quando você está com energia demais',
  ],

  // FASE 2: escala/absurdo — bom pra discussão comparativa
  phase2Themes: [
    'Pior coisa para se fazer num velório',
    'A última coisa que você faria num apocalipse zumbi',
    'A coisa mais absurda de se fazer numa reunião importante',
    'A coisa menos apropriada para se fazer numa entrevista de emprego',
    'A primeira coisa a se fazer ao acordar em Marte',
    'Pior coisa para se fazer quando você encontra seu ex',
    'A última coisa a fazer quando o chefe diz “rapidinho”',
    'A coisa mais suspeita para se fazer num elevador silencioso',
    'A pior coisa para se fazer num casamento (na hora dos votos)',
    'A coisa menos apropriada para se fazer numa formatura',
    'A pior coisa para se fazer quando você mandou mensagem no grupo errado',
    'A coisa mais dramática para se fazer no mercado às 22h',
    'A última coisa que você faria se ficasse invisível por 10 minutos',
    'A coisa mais arriscada para se fazer num aeroporto lotado',
    'A coisa menos heroica para se fazer no fim do mundo',
    'A coisa mais “vilão de novela” para se fazer num almoço de família',
    'A pior coisa para se fazer quando você está tentando parecer adulto responsável',
    'A pior coisa para se fazer quando o Wi-Fi volta depois de cair',
    'A coisa menos apropriada para se fazer num primeiro encontro',
    'A coisa mais esquisita para se fazer numa biblioteca',
    'A coisa mais constrangedora para se fazer ao falar em público',
    'A coisa mais suspeita para se fazer quando você é confundido com o gerente',
    'A última coisa que você faria numa nave espacial com alarme tocando',
    'A coisa mais errada para se fazer num teste psicológico',
    'A coisa mais engraçada para se fazer quando todo mundo está sério',
    'A coisa menos recomendada para se fazer durante uma tempestade',
    'A pior coisa para se fazer numa prova importante',
    'A pior coisa para se fazer numa chamada de vídeo com câmera ligada',
    'A coisa menos apropriada para se fazer em um museu',
    'A primeira coisa que você faria se acordasse num filme de terror',
    'A pior coisa para se fazer quando você percebe que está sendo observado',
    'A coisa mais absurda para se fazer numa audiência importante',
    'A pior coisa para se fazer quando você está perdido sem GPS',
    'A coisa menos apropriada para se fazer quando alguém te dá um presente',
    'A coisa mais caótica para se fazer num evento chique',
    'A última coisa que você faria antes de um anúncio “senhoras e senhores…”',
    'A pior coisa para se fazer quando você tenta ser discreto',
    'A coisa mais suspeita para se fazer numa sala de espera',
    'A pior coisa para se fazer quando você quer causar boa impressão',
    'A coisa mais estranha para se fazer num silêncio constrangedor',
    'A coisa menos apropriada para se fazer quando alguém está chorando',
    'A coisa mais perigosa para se fazer quando você está “quase sendo pego”',
    'A primeira coisa a se fazer ao descobrir que você é um personagem secundário',
    'A coisa menos apropriada para se fazer numa reunião com sogros',
    'A pior coisa para se fazer quando você está atrasado',
    'A coisa mais absurda para se fazer numa cerimônia solene',
  ],
};
